# -*- coding: utf-8 -*-
"""week9_embeddings_day2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gc-HDCCQinJwmrBYo4ugTCavoRrq_WB0
"""

from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('all-MiniLM-L6-v2')

paragraph = """Python is a programming language. It is used for web development,
data science, and automation. Many beginners start with Python because of its
simple syntax. The language was created by Guido van Rossum in 1991.
It supports multiple programming paradigms."""

sentences = [
    "Python is a programming language.",
    "It is used for web development, data science, and automation.",
    "Many beginners start with Python because of its simple syntax.",
    "The language was created by Guido van Rossum in 1991.",
    "It supports multiple programming paradigms."
]

question = "Who created Python?"

para_embedding = model.encode(paragraph)
sentence_embeddings = model.encode(sentences)
question_embedding = model.encode(question)

para_score = util.cos_sim(para_embedding, question_embedding)
print(f"Paragraph Embedding Score: {para_score.item()}")
print()
for i in range(len(sentences)):
  sent_score = util.cos_sim(sentence_embeddings[i],question_embedding)
  print(f"Score: {sent_score.item()}")
  print(f"  '{sentences[i]}'")
  print()

"""Chunking exists because embedding a long, mixed-topic document produces one diluted embedding that doesn't match any specific question well. Splitting into smaller, focused chunks gives the retriever distinct, precise embeddings to search across.

Chunks that are too small can lose the surrounding context needed to understand them — a sentence might mention "he" or "it" without saying who or what, so its embedding won't match a question that uses the specific name.
"""