# -*- coding: utf-8 -*-
"""week9_embeddings_day3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FwwYz9TN1oexwCDB_Qtpw0LxzvzqFpzw
"""

def chunk_text(text, chunk_size, overlap):
  start = 0
  l = []
  l.append(text[0:chunk_size])
  chunk_update = chunk_size
  while start <= len(text):
    l.append(text[chunk_update-overlap: chunk_update-overlap+chunk_size])
    chunk_update = chunk_update-overlap+chunk_size
    start = chunk_update


  return l


document = """
Company Refund Policy

Our refund policy is designed to be fair to both customers and the business.
Customers may request a refund for any item purchased within the last 30 days
from the date of delivery. After this 30 day period, no refunds will be issued
under any circumstances, even for defective products.

To request a refund, customers must contact our support team through the
official email address with their order number and reason for the return.
Refunds are typically processed within 5 to 7 business days after approval.

Exceptions to this policy include digital products, which are non-refundable
once downloaded, and items marked as final sale at the time of purchase.
Shipping costs are non-refundable in all cases, regardless of the reason
for the return.

Customers who receive damaged or defective items are eligible for a full
refund including shipping costs, but must report the issue within 7 days
of delivery with photographic evidence of the damage.
"""


print("Total characters in document:", len(document))

chunks = chunk_text(document, 200, 54)
for i, c in enumerate(chunks):
    print(f"Chunk {i+1} (length {len(c)}):")
    print(c)
    print()