# -*- coding: utf-8 -*-
"""week9_embeddings_day5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KfKQ6CAieluhRDp32iW11a2pF34yl-N5
"""

from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('all-MiniLM-L6-v2')

def chunk_text(text, chunk_size, overlap):
  start = 0
  l = []
  l.append(text[0:chunk_size])
  chunk_update = chunk_size
  while start <= len(text):
    l.append(text[chunk_update-overlap: chunk_update-overlap+chunk_size])
    chunk_update = chunk_update-overlap+chunk_size
    start = chunk_update


  return l

document = """
Employee Handbook — TechCorp India

Section 1: Working Hours
All full-time employees are expected to work 9 hours per day, Monday through Friday.
Core hours are between 10 AM and 4 PM, during which all employees must be available.
Flexible working hours are allowed outside of core hours with manager approval.
Remote work is permitted up to 2 days per week for roles that do not require physical presence.
Overtime work must be pre-approved by the department head and compensated accordingly.

Section 2: Leave Policy
Employees are entitled to 18 days of paid annual leave per calendar year.
Sick leave is capped at 10 days per year and requires a medical certificate for absences exceeding 3 consecutive days.
Maternity leave is 26 weeks as per government regulations.
Paternity leave is 5 working days, to be availed within 3 months of the child's birth.
Casual leave of 6 days per year may be taken without prior approval for emergencies.

Section 3: Code of Conduct
Employees must maintain professional behavior at all times in the workplace.
Harassment of any kind, including verbal, physical, or digital, will result in immediate termination.
Confidential company information must not be shared with external parties under any circumstances.
Employees found engaging in conflicts of interest must disclose them to HR immediately.
Use of company resources for personal projects is strictly prohibited.

Section 4: Salary and Benefits
Salaries are credited on the last working day of each month.
Employees are eligible for a performance bonus of up to 20% of annual salary, reviewed every April.
Health insurance coverage of up to 5 lakhs per annum is provided for employees and their immediate family.
Provident Fund contributions are deducted at 12% of basic salary as per government mandate.
Employees with more than 3 years of service are eligible for gratuity as per the Payment of Gratuity Act.

Section 5: Resignation and Exit
Employees must serve a notice period of 60 days before their last working day.
Notice period buyout is allowed at the discretion of the management.
Full and final settlement is processed within 45 days of the last working day.
Experience letters and relieving letters are issued within 7 days of full and final settlement.
Employees who leave without serving notice will forfeit their pending leaves and bonus.
"""

print("Total characters:", len(document))
chunks = chunk_text(document, 550, 100)
chunk_embeddings = model.encode(chunks)
questions = model.encode(["How many days of annual leave do employees get?",
"What happens if an employee resigns without notice?",
"What is the health insurance coverage amount?"])
for x,ques in enumerate(questions):
  print(f"Question : {x+1}")
  print()
  for i, c in enumerate(chunks):
    print(f"Score: {util.cos_sim(chunk_embeddings[i],ques)}")
    print(f"Chunk {i+1} Preview:  {c}....")
    print()
    print("******* END ********")

sections = document.split("Section")
for i, s in enumerate(sections):
  print(f"Section {i} length: {len(s)} characters")
  print()

