# -*- coding: utf-8 -*-
"""week9_embeddings_day4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zFI58m0h8gxAqKeQpEmC--wHS93Z5rSV
"""

from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('all-MiniLM-L6-v2')

def chunk_text(text, chunk_size, overlap):
  start = 0
  l = []
  l.append(text[0:chunk_size])
  chunk_update = chunk_size
  while start <= len(text):
    l.append(text[chunk_update-overlap: chunk_update-overlap+chunk_size])
    chunk_update = chunk_update-overlap+chunk_size
    start = chunk_update


  return l



document = """
Company Refund Policy

Our refund policy is designed to be fair to both customers and the business.
Customers may request a refund for any item purchased within the last 30 days
from the date of delivery. After this 30 day period, no refunds will be issued
under any circumstances, even for defective products.

To request a refund, customers must contact our support team through the
official email address with their order number and reason for the return.
Refunds are typically processed within 5 to 7 business days after approval.

Exceptions to this policy include digital products, which are non-refundable
once downloaded, and items marked as final sale at the time of purchase.
Shipping costs are non-refundable in all cases, regardless of the reason
for the return.

Customers who receive damaged or defective items are eligible for a full
refund including shipping costs, but must report the issue within 7 days
of delivery with photographic evidence of the damage.
"""

print(len(document))
chunks = chunk_text(document, 400, 80)
chunk_embeddings = model.encode(chunks)
question_embedding = model.encode("What is the deadline to report a damaged item?")

for i, c in enumerate(chunks):
    print(f"Score: {util.cos_sim(chunk_embeddings[i],question_embedding)}")
    print(f"Chunk {i+1} Preview:  {c}....")
    print()
    print("***")

"""Day 4 Complete
Here is what i built and proved today with real numbers:

I embedded all chunks and built a working retrieval loop from scratch
I verified your prediction — Chunk 6 and 7 scored highest with chunk_size=200
I caught that Chunk 7 was not self-contained — the answer was split across two chunks
I proved that overlap=54 was too small to carry the subject across the boundary
I ran the same experiment with chunk_size=400 and saw the answer contained in one chunk
I reasoned out the tradeoff — bigger chunks fix boundary splits but dilute embedding specificity
"""